### ISSUE TITLE
按图索骥丢官服7.1.1的链接进去build，但为什么失败了？

### ISSUE THREAD

**Issue by JtVast** [liusj5257/azurlane_anti_name#29]
Zipalign and Sign Android release这里报错了
Error: Exception in thread "main" java.io.FileNotFoundException: build/*.apk (No such file or directory)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:344)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:213)
	at com.android.apksig.ApkSigner.sign(ApkSigner.java:190)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:381)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:88)
Error: Process completed with exit code 1.

**Comment by liusj5257** [comment]
看下buildapk step,没下载到apk,后续所有步骤都失效

**Comment by JtVast** [comment]
> 看下buildapk step,没下载到apk,后续所有步骤都失效

绝了，晚上回家换了台电脑就行了。。。。
